name: Controle de Qualidade (CI)

on:
  push:
    branches: [ "principal" ]
  pull_request:
    branches: [ "principal" ]

jobs:
  testes:
    runs-on: ubuntu-latest

    steps:
    - name: Copiar os arquivos do repositório
      uses: actions/checkout@v4

    - name: Configurar o Python no servidor
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Instalar o Pytest
      run: pip install pytest

    - name: Executar testes automatizados
      run: pytest src/sistema.py